config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  root 'recipes#index'

end

app/models/recipe.rb
class Recipe
  include HTTParty

  key_value = ENV['FOOD2FORK_KEY']
  hostport = ENV['FOOD2FORK_SERVER_AND_PORT'] || 'www.food2fork.com'

  base_uri "http://#{hostport}/api"
  default_params key: key_value
  format :json

  def self.for keyword
    get("/search", query: { q:keyword })["recipes"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
    @search_query = params[:search] || 'Chocolate'
    @recipes = Recipe.for(@search_query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipefinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = "container">
<%= yield %>
<p class ="powered">
Powered	By Food2Fork.com 
</p>
</div>
</body>
</html>

app/views/recipes/_search.html.erb
<%=form_tag(recipes_index_path, :method => 'get') do %>	
<p class = search_bar>
	<%= text_field_tag :search, params[:search], placeholder: "Search"%>
	
	<%= submit_tag "Search"%>
	</p>
<% end%>

<%= link_to "Back"%>

app/views/recipes/index.html.erb
<%= render 'recipes/search'%>
<h3>Search results for <%= @search_query %></h3>
<table border ="1">
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Ranking</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to image_tag(recipe["image_url"], size: "100x100"), recipe["f2f_url"] %></td>
        <td><%= link_to(sanitize(recipe["title"]), recipe["f2f_url"]) %></td>
        <td><%= recipe["social_rank"].to_i %></td>
      </tr>
    <% end %>
  </tbody>
</table>